create table localorder(
       ID guid primary key not null,
       CustomerName text not null,
       PO text,
       Composition text not null,
       CompositionDetail text,
       ProductType text,
       Purity text,
       Quantity real,
       QuantityUnit  text,
       Dimension  text,
       DimensionDetails  text,
       Drawing  text,
       SampleNeed  text,
       SampleNeedRemark text,
       SampleForAnlysis text,
       SampleForAnlysisRemark text,   
       DeadLine  datetime,
       MiniumAcceptDefect text,
       ShipTo text,
       WithBackingPlate  text,
       PlateDrawing  text,
       SpecialRequirement text,
       BondingRequirement  text,
       PartNumber  text,  
       Remark  text,
       CreateTime DateTime,
       OrderState text
          
)