//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSEOrder.PMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMS.IEOrderService")]
    public interface IEOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEOrderService/CheckEOrderGuid", ReplyAction="http://tempuri.org/IEOrderService/CheckEOrderGuidResponse")]
        bool CheckEOrderGuid(string guidid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEOrderService/CheckEOrderGuid", ReplyAction="http://tempuri.org/IEOrderService/CheckEOrderGuidResponse")]
        System.Threading.Tasks.Task<bool> CheckEOrderGuidAsync(string guidid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEOrderServiceChannel : PMSEOrder.PMS.IEOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EOrderServiceClient : System.ServiceModel.ClientBase<PMSEOrder.PMS.IEOrderService>, PMSEOrder.PMS.IEOrderService {
        
        public EOrderServiceClient() {
        }
        
        public EOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckEOrderGuid(string guidid) {
            return base.Channel.CheckEOrderGuid(guidid);
        }
        
        public System.Threading.Tasks.Task<bool> CheckEOrderGuidAsync(string guidid) {
            return base.Channel.CheckEOrderGuidAsync(guidid);
        }
    }
}
