//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSClient.HeartBeatService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HeartBeatService.IHeartBeatSerive")]
    public interface IHeartBeatSerive {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeartBeatSerive/Beat", ReplyAction="http://tempuri.org/IHeartBeatSerive/BeatResponse")]
        string Beat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeartBeatSerive/Beat", ReplyAction="http://tempuri.org/IHeartBeatSerive/BeatResponse")]
        System.Threading.Tasks.Task<string> BeatAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeartBeatSeriveChannel : PMSClient.HeartBeatService.IHeartBeatSerive, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeartBeatSeriveClient : System.ServiceModel.ClientBase<PMSClient.HeartBeatService.IHeartBeatSerive>, PMSClient.HeartBeatService.IHeartBeatSerive {
        
        public HeartBeatSeriveClient() {
        }
        
        public HeartBeatSeriveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeartBeatSeriveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeartBeatSeriveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeartBeatSeriveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Beat() {
            return base.Channel.Beat();
        }
        
        public System.Threading.Tasks.Task<string> BeatAsync() {
            return base.Channel.BeatAsync();
        }
    }
}
