namespace PMSDAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class change14 : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.DeliveryHistories");
            DropPrimaryKey("dbo.DeliveryItemHistories");
            DropPrimaryKey("dbo.MaterialInventoryInHistories");
            DropPrimaryKey("dbo.MaterialInventoryOutHistories");
            DropPrimaryKey("dbo.MaterialNeedHistories");
            DropPrimaryKey("dbo.MaterialOrderHistories");
            DropPrimaryKey("dbo.MaterialOrderItemHistories");
            DropPrimaryKey("dbo.PMSOrderHistories");
            DropPrimaryKey("dbo.ProductHistories");
            DropPrimaryKey("dbo.RecordBondingHistories");
            DropPrimaryKey("dbo.RecordDeMoldHistories");
            DropPrimaryKey("dbo.RecordMachineHistories");
            DropPrimaryKey("dbo.RecordMillingHistories");
            DropPrimaryKey("dbo.RecordTestHistories");
            DropPrimaryKey("dbo.RecordVHPHistories");
            DropPrimaryKey("dbo.PMSPlanVHPHistories");
            AddColumn("dbo.DeliveryHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.DeliveryItemHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.MaterialInventoryInHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.MaterialInventoryOutHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.MaterialNeedHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.MaterialOrderHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.MaterialOrderItemHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.PMSOrderHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.PMSOrderHistories", "Operator", c => c.String());
            AddColumn("dbo.PMSOrderHistories", "OperateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.ProductHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.RecordBondingHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.RecordDeMoldHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.RecordDeMoldHistories", "BlankDimension", c => c.String());
            AddColumn("dbo.RecordDeMoldHistories", "CalculationDensity", c => c.Double(nullable: false));
            AddColumn("dbo.RecordDeMoldHistories", "Density", c => c.Double(nullable: false));
            AddColumn("dbo.RecordDeMoldHistories", "RatioDensity", c => c.Double(nullable: false));
            AddColumn("dbo.RecordDeMolds", "BlankDimension", c => c.String());
            AddColumn("dbo.RecordDeMolds", "CalculationDensity", c => c.Double(nullable: false));
            AddColumn("dbo.RecordDeMolds", "Density", c => c.Double(nullable: false));
            AddColumn("dbo.RecordDeMolds", "RatioDensity", c => c.Double(nullable: false));
            AddColumn("dbo.RecordMachineHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.RecordMillingHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.RecordTestHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.RecordTestHistories", "OrderDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RecordTests", "OrderDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.RecordVHPHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.PMSPlanVHPHistories", "HistoryID", c => c.Guid(nullable: false));
            AddColumn("dbo.PMSPlanVHPHistories", "Operator", c => c.String());
            AddColumn("dbo.PMSPlanVHPHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.DeliveryHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.DeliveryItemHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MaterialInventoryInHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MaterialInventoryOutHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MaterialNeedHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MaterialOrderHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MaterialOrderItemHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ProductHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RecordBondingHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RecordDeMoldHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RecordMachineHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RecordMillingHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RecordTestHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.RecordVHPHistories", "OperateTime", c => c.DateTime(nullable: false));
            AlterColumn("dbo.PMSPlanVHPHistories", "Remark", c => c.DateTime(nullable: false));
            AddPrimaryKey("dbo.DeliveryHistories", "HistoryID");
            AddPrimaryKey("dbo.DeliveryItemHistories", "HistoryID");
            AddPrimaryKey("dbo.MaterialInventoryInHistories", "HistoryID");
            AddPrimaryKey("dbo.MaterialInventoryOutHistories", "HistoryID");
            AddPrimaryKey("dbo.MaterialNeedHistories", "HistoryID");
            AddPrimaryKey("dbo.MaterialOrderHistories", "HistoryID");
            AddPrimaryKey("dbo.MaterialOrderItemHistories", "HistoryID");
            AddPrimaryKey("dbo.PMSOrderHistories", "HistoryID");
            AddPrimaryKey("dbo.ProductHistories", "HistoryID");
            AddPrimaryKey("dbo.RecordBondingHistories", "HistoryID");
            AddPrimaryKey("dbo.RecordDeMoldHistories", "HistoryID");
            AddPrimaryKey("dbo.RecordMachineHistories", "HistoryID");
            AddPrimaryKey("dbo.RecordMillingHistories", "HistoryID");
            AddPrimaryKey("dbo.RecordTestHistories", "HistoryID");
            AddPrimaryKey("dbo.RecordVHPHistories", "HistoryID");
            AddPrimaryKey("dbo.PMSPlanVHPHistories", "HistoryID");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.PMSPlanVHPHistories");
            DropPrimaryKey("dbo.RecordVHPHistories");
            DropPrimaryKey("dbo.RecordTestHistories");
            DropPrimaryKey("dbo.RecordMillingHistories");
            DropPrimaryKey("dbo.RecordMachineHistories");
            DropPrimaryKey("dbo.RecordDeMoldHistories");
            DropPrimaryKey("dbo.RecordBondingHistories");
            DropPrimaryKey("dbo.ProductHistories");
            DropPrimaryKey("dbo.PMSOrderHistories");
            DropPrimaryKey("dbo.MaterialOrderItemHistories");
            DropPrimaryKey("dbo.MaterialOrderHistories");
            DropPrimaryKey("dbo.MaterialNeedHistories");
            DropPrimaryKey("dbo.MaterialInventoryOutHistories");
            DropPrimaryKey("dbo.MaterialInventoryInHistories");
            DropPrimaryKey("dbo.DeliveryItemHistories");
            DropPrimaryKey("dbo.DeliveryHistories");
            AlterColumn("dbo.PMSPlanVHPHistories", "Remark", c => c.String());
            AlterColumn("dbo.RecordVHPHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.RecordTestHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.RecordMillingHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.RecordMachineHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.RecordDeMoldHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.RecordBondingHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.ProductHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.MaterialOrderItemHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.MaterialOrderHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.MaterialNeedHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.MaterialInventoryOutHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.MaterialInventoryInHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.DeliveryItemHistories", "OperateTime", c => c.String());
            AlterColumn("dbo.DeliveryHistories", "OperateTime", c => c.String());
            DropColumn("dbo.PMSPlanVHPHistories", "OperateTime");
            DropColumn("dbo.PMSPlanVHPHistories", "Operator");
            DropColumn("dbo.PMSPlanVHPHistories", "HistoryID");
            DropColumn("dbo.RecordVHPHistories", "HistoryID");
            DropColumn("dbo.RecordTests", "OrderDate");
            DropColumn("dbo.RecordTestHistories", "OrderDate");
            DropColumn("dbo.RecordTestHistories", "HistoryID");
            DropColumn("dbo.RecordMillingHistories", "HistoryID");
            DropColumn("dbo.RecordMachineHistories", "HistoryID");
            DropColumn("dbo.RecordDeMolds", "RatioDensity");
            DropColumn("dbo.RecordDeMolds", "Density");
            DropColumn("dbo.RecordDeMolds", "CalculationDensity");
            DropColumn("dbo.RecordDeMolds", "BlankDimension");
            DropColumn("dbo.RecordDeMoldHistories", "RatioDensity");
            DropColumn("dbo.RecordDeMoldHistories", "Density");
            DropColumn("dbo.RecordDeMoldHistories", "CalculationDensity");
            DropColumn("dbo.RecordDeMoldHistories", "BlankDimension");
            DropColumn("dbo.RecordDeMoldHistories", "HistoryID");
            DropColumn("dbo.RecordBondingHistories", "HistoryID");
            DropColumn("dbo.ProductHistories", "HistoryID");
            DropColumn("dbo.PMSOrderHistories", "OperateTime");
            DropColumn("dbo.PMSOrderHistories", "Operator");
            DropColumn("dbo.PMSOrderHistories", "HistoryID");
            DropColumn("dbo.MaterialOrderItemHistories", "HistoryID");
            DropColumn("dbo.MaterialOrderHistories", "HistoryID");
            DropColumn("dbo.MaterialNeedHistories", "HistoryID");
            DropColumn("dbo.MaterialInventoryOutHistories", "HistoryID");
            DropColumn("dbo.MaterialInventoryInHistories", "HistoryID");
            DropColumn("dbo.DeliveryItemHistories", "HistoryID");
            DropColumn("dbo.DeliveryHistories", "HistoryID");
            AddPrimaryKey("dbo.PMSPlanVHPHistories", "ID");
            AddPrimaryKey("dbo.RecordVHPHistories", "ID");
            AddPrimaryKey("dbo.RecordTestHistories", "ID");
            AddPrimaryKey("dbo.RecordMillingHistories", "ID");
            AddPrimaryKey("dbo.RecordMachineHistories", "ID");
            AddPrimaryKey("dbo.RecordDeMoldHistories", "ID");
            AddPrimaryKey("dbo.RecordBondingHistories", "ID");
            AddPrimaryKey("dbo.ProductHistories", "ID");
            AddPrimaryKey("dbo.PMSOrderHistories", "ID");
            AddPrimaryKey("dbo.MaterialOrderItemHistories", "ID");
            AddPrimaryKey("dbo.MaterialOrderHistories", "ID");
            AddPrimaryKey("dbo.MaterialNeedHistories", "Id");
            AddPrimaryKey("dbo.MaterialInventoryOutHistories", "Id");
            AddPrimaryKey("dbo.MaterialInventoryInHistories", "Id");
            AddPrimaryKey("dbo.DeliveryItemHistories", "ID");
            AddPrimaryKey("dbo.DeliveryHistories", "ID");
        }
    }
}
