// <auto-generated />
namespace PMSDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtorecordvhp2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtorecordvhp2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701220801076_addtorecordvhp2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
