//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSClient.PMSIndexService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMSIndexService.IPMSIndexService")]
    public interface IPMSIndexService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSIndexService/CalculateProductionIndex", ReplyAction="http://tempuri.org/IPMSIndexService/CalculateProductionIndexResponse")]
        void CalculateProductionIndex(System.Guid orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSIndexService/CalculateProductionIndex", ReplyAction="http://tempuri.org/IPMSIndexService/CalculateProductionIndexResponse")]
        System.Threading.Tasks.Task CalculateProductionIndexAsync(System.Guid orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSIndexService/CalculateMaterialIndex", ReplyAction="http://tempuri.org/IPMSIndexService/CalculateMaterialIndexResponse")]
        void CalculateMaterialIndex(System.Guid orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMSIndexService/CalculateMaterialIndex", ReplyAction="http://tempuri.org/IPMSIndexService/CalculateMaterialIndexResponse")]
        System.Threading.Tasks.Task CalculateMaterialIndexAsync(System.Guid orderid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPMSIndexServiceChannel : PMSClient.PMSIndexService.IPMSIndexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMSIndexServiceClient : System.ServiceModel.ClientBase<PMSClient.PMSIndexService.IPMSIndexService>, PMSClient.PMSIndexService.IPMSIndexService {
        
        public PMSIndexServiceClient() {
        }
        
        public PMSIndexServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMSIndexServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMSIndexServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMSIndexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CalculateProductionIndex(System.Guid orderid) {
            base.Channel.CalculateProductionIndex(orderid);
        }
        
        public System.Threading.Tasks.Task CalculateProductionIndexAsync(System.Guid orderid) {
            return base.Channel.CalculateProductionIndexAsync(orderid);
        }
        
        public void CalculateMaterialIndex(System.Guid orderid) {
            base.Channel.CalculateMaterialIndex(orderid);
        }
        
        public System.Threading.Tasks.Task CalculateMaterialIndexAsync(System.Guid orderid) {
            return base.Channel.CalculateMaterialIndexAsync(orderid);
        }
    }
}
