//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOrderItems
    {
        public System.Guid ID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Creator { get; set; }
        public string State { get; set; }
        public string Composition { get; set; }
        public string Purity { get; set; }
        public string Description { get; set; }
        public string ProvideRawMaterial { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public double UnitPrice { get; set; }
        public double Weight { get; set; }
        public Nullable<System.Guid> MaterialOrderID { get; set; }
        public string PMINumber { get; set; }
        public string OrderItemNumber { get; set; }
    
        public virtual MaterialOrders MaterialOrders { get; set; }
    }
}
