//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInventoryOuts
    {
        public System.Guid Id { get; set; }
        public string State { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string MaterialLot { get; set; }
        public string PMINumber { get; set; }
        public string Composition { get; set; }
        public string Purity { get; set; }
        public string Receiver { get; set; }
        public double Weight { get; set; }
        public string Remark { get; set; }
    }
}
