//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<BDCompounds> BDCompounds { get; set; }
        public virtual DbSet<BDCustomers> BDCustomers { get; set; }
        public virtual DbSet<BDDeliveryAddresses> BDDeliveryAddresses { get; set; }
        public virtual DbSet<BDElementGroupItems> BDElementGroupItems { get; set; }
        public virtual DbSet<BDElementGroups> BDElementGroups { get; set; }
        public virtual DbSet<BDElements> BDElements { get; set; }
        public virtual DbSet<BDSieves> BDSieves { get; set; }
        public virtual DbSet<BDSuppliers> BDSuppliers { get; set; }
        public virtual DbSet<BDVHPDevices> BDVHPDevices { get; set; }
        public virtual DbSet<BDVHPMolds> BDVHPMolds { get; set; }
        public virtual DbSet<BDVHPProcesses> BDVHPProcesses { get; set; }
        public virtual DbSet<Deliveries> Deliveries { get; set; }
        public virtual DbSet<DeliveryItems> DeliveryItems { get; set; }
        public virtual DbSet<LogErrors> LogErrors { get; set; }
        public virtual DbSet<LogInformations> LogInformations { get; set; }
        public virtual DbSet<MaintenancePlans> MaintenancePlans { get; set; }
        public virtual DbSet<MaintenanceRecords> MaintenanceRecords { get; set; }
        public virtual DbSet<MaterialInventoryIns> MaterialInventoryIns { get; set; }
        public virtual DbSet<MaterialInventoryOuts> MaterialInventoryOuts { get; set; }
        public virtual DbSet<MaterialNeeds> MaterialNeeds { get; set; }
        public virtual DbSet<MaterialOrderItems> MaterialOrderItems { get; set; }
        public virtual DbSet<MaterialOrders> MaterialOrders { get; set; }
        public virtual DbSet<PMSOrders> PMSOrders { get; set; }
        public virtual DbSet<PMSPlanVHPs> PMSPlanVHPs { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<RecordBondings> RecordBondings { get; set; }
        public virtual DbSet<RecordDeMolds> RecordDeMolds { get; set; }
        public virtual DbSet<RecordMachines> RecordMachines { get; set; }
        public virtual DbSet<RecordMillings> RecordMillings { get; set; }
        public virtual DbSet<RecordTests> RecordTests { get; set; }
        public virtual DbSet<RecordVHPs> RecordVHPs { get; set; }
        public virtual DbSet<UserAccesses> UserAccesses { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
