//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSPlanVHPs
    {
        public System.Guid ID { get; set; }
        public string State { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid OrderID { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string VHPDeviceCode { get; set; }
        public double CalculationDensity { get; set; }
        public double MoldDiameter { get; set; }
        public double Thickness { get; set; }
        public int Quantity { get; set; }
        public string GrainSize { get; set; }
        public string MillingRequirement { get; set; }
        public double RoomTemperature { get; set; }
        public double RoomHumidity { get; set; }
        public double PreTemperature { get; set; }
        public double PrePressure { get; set; }
        public double Temperature { get; set; }
        public double Pressure { get; set; }
        public double Vaccum { get; set; }
        public double KeepTempTime { get; set; }
        public string SpecialRequirement { get; set; }
        public string FillingRequirement { get; set; }
        public string Remark { get; set; }
        public string ProcessCode { get; set; }
        public string VHPRequirement { get; set; }
        public string MachineRequirement { get; set; }
        public string MoldType { get; set; }
        public int PlanLot { get; set; }
        public double SingleWeight { get; set; }
        public double AllWeight { get; set; }
    
        public virtual PMSOrders PMSOrders { get; set; }
    }
}
