//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordBondings
    {
        public System.Guid ID { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string State { get; set; }
        public string InstructionCode { get; set; }
        public string TargetComposition { get; set; }
        public string TargetAppearance { get; set; }
        public string TargetWarpageCheck { get; set; }
        public string TargetThicknessCheck { get; set; }
        public string TargetDiameterCheck { get; set; }
        public System.DateTime TargetCheckTime { get; set; }
        public string PlateLot { get; set; }
        public string PlateMaterial { get; set; }
        public string PlateBelong { get; set; }
        public string PlateDimension { get; set; }
        public string PlateUseCount { get; set; }
        public string PlateHardness { get; set; }
        public string PlateSuplier { get; set; }
        public string PlateAppearance { get; set; }
        public System.DateTime PlateCheckTime { get; set; }
        public string WeldMaterial { get; set; }
        public string TargetProductID { get; set; }
        public string TargetAbbr { get; set; }
        public string TargetCustomer { get; set; }
        public string TargetPO { get; set; }
        public string TargetWeight { get; set; }
        public string TargetDetailRecord { get; set; }
        public string TargetDimensionActual { get; set; }
        public string TargetPerson { get; set; }
        public string PlateLastWeldMaterial { get; set; }
        public string PlateOtherRecord { get; set; }
        public string PlatePerson { get; set; }
        public string TargetPreProcessRecord { get; set; }
        public string TargetPreProcessPerson { get; set; }
        public System.DateTime TargetPreProcessCheckTime { get; set; }
        public string PlatePreProcessRecord { get; set; }
        public string PlatePreProcessPerson { get; set; }
        public System.DateTime PlatePreProcessCheckTime { get; set; }
        public string WeldCuStringDiameter { get; set; }
        public string WeldHold { get; set; }
        public string WeldPerson { get; set; }
        public System.DateTime WeldCheckTime { get; set; }
        public string WarpageFix { get; set; }
        public string WarpagePerson { get; set; }
        public System.DateTime WarpageCheckTime { get; set; }
        public string DimensionCheck { get; set; }
        public string DimensionWarpageCheck { get; set; }
        public string DimensionPerson { get; set; }
        public System.DateTime DimensionCheckTime { get; set; }
        public string BindingCheck { get; set; }
        public string BindingPerson { get; set; }
        public System.DateTime BindingCheckTime { get; set; }
        public string SprayCheck { get; set; }
        public string SprayPerson { get; set; }
        public System.DateTime SprayCheckTime { get; set; }
        public string CleanCheck { get; set; }
        public string CleanPerson { get; set; }
        public System.DateTime CleanCheckTime { get; set; }
        public string ApperanceCheck { get; set; }
        public string ApperancePerson { get; set; }
        public System.DateTime ApperanceCheckTime { get; set; }
        public string PackCheck { get; set; }
        public string PackPerson { get; set; }
        public System.DateTime PackCheckTime { get; set; }
        public string TargetDimension { get; set; }
        public string TargetDefects { get; set; }
    }
}
