//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Plan()
        {
            this.tb_RMachine = new HashSet<tb_RMachine>();
            this.tb_RPack = new HashSet<tb_RPack>();
            this.tb_RPowder = new HashSet<tb_RPowder>();
            this.tb_RVHP = new HashSet<tb_RVHP>();
            this.tb_RWash = new HashSet<tb_RWash>();
        }
    
        public int OrderID { get; set; }
        public int PlanID { get; set; }
        public System.DateTime VHPTimePlan { get; set; }
        public Nullable<double> MoldMD { get; set; }
        public Nullable<double> PressThick { get; set; }
        public Nullable<int> PressNum { get; set; }
        public string DeviceType { get; set; }
        public string PowderRequire { get; set; }
        public string FillRequire { get; set; }
        public string MachineRequire { get; set; }
        public string HighestPressure { get; set; }
        public string HighestTemp { get; set; }
        public string PlanMemo { get; set; }
        public Nullable<bool> IsOkToSend { get; set; }
        public Nullable<double> DensityCal { get; set; }
        public Nullable<double> WeightS { get; set; }
        public Nullable<double> WeightAll { get; set; }
        public string PersonInCharge { get; set; }
    
        public virtual tb_Order tb_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RMachine> tb_RMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RPack> tb_RPack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RPowder> tb_RPowder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RVHP> tb_RVHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_RWash> tb_RWash { get; set; }
    }
}
