//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTransferFromOldToNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_RVHP
    {
        public int PlanID { get; set; }
        public int VHPID { get; set; }
        public Nullable<System.DateTime> WD_FP { get; set; }
        public string WM_FP { get; set; }
        public string FillW1 { get; set; }
        public string FillW2 { get; set; }
        public string FillWP1 { get; set; }
        public string FillWP2 { get; set; }
        public string FPMemo { get; set; }
        public string WM_VHP { get; set; }
        public string VHPMemo { get; set; }
        public Nullable<System.DateTime> WD_TM { get; set; }
        public string WM_TM { get; set; }
        public string TM_Temp { get; set; }
        public string TM_Method { get; set; }
        public string TM_Memo { get; set; }
        public Nullable<System.DateTime> WD_M { get; set; }
        public string WM_M { get; set; }
        public string MW1 { get; set; }
        public string MW2 { get; set; }
        public string MWL1 { get; set; }
        public string MWL2 { get; set; }
        public string MD1 { get; set; }
        public string MD2 { get; set; }
        public string MD3 { get; set; }
        public string MD4 { get; set; }
        public string MH1 { get; set; }
        public string MH2 { get; set; }
        public string MH3 { get; set; }
        public string MH4 { get; set; }
        public string MH5 { get; set; }
        public string MH6 { get; set; }
        public string MH7 { get; set; }
        public string MH8 { get; set; }
        public Nullable<System.DateTime> WD_Left { get; set; }
        public string WM_Left { get; set; }
        public string Method_Left { get; set; }
        public string Method_Cold { get; set; }
        public string Memo_Left { get; set; }
    
        public virtual tb_Plan tb_Plan { get; set; }
    }
}
